# Generated by Django 5.0.3 on 2024-08-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.TextField(default='sth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.TextField(default='sth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='isbn',
            field=models.TextField(default='sth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.TextField(default='sth'),
            preserve_default=False,
        ),
    ]
